// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PartnerControlAPI.Data;

#nullable disable

namespace PartnerControlAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250605100138_UpdateDiscountSettingsWithRules")]
    partial class UpdateDiscountSettingsWithRules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PartnerControlAPI.Models.DiscountSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long>("MaxAmount")
                        .HasColumnType("bigint");

                    b.Property<long>("MinAmount")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DiscountSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "No discount for amounts less than MYR 200",
                            DiscountPercentage = 0,
                            IsActive = true,
                            MaxAmount = 199L,
                            MinAmount = 0L,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "5% discount for amounts between MYR 200 and MYR 500",
                            DiscountPercentage = 5,
                            IsActive = true,
                            MaxAmount = 500L,
                            MinAmount = 200L,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "7% discount for amounts between MYR 501 and MYR 800",
                            DiscountPercentage = 7,
                            IsActive = true,
                            MaxAmount = 800L,
                            MinAmount = 501L,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "10% discount for amounts between MYR 801 and MYR 1200",
                            DiscountPercentage = 10,
                            IsActive = true,
                            MaxAmount = 1200L,
                            MinAmount = 801L,
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "15% discount for amounts above MYR 1200",
                            DiscountPercentage = 15,
                            IsActive = true,
                            MaxAmount = 9223372036854775807L,
                            MinAmount = 1201L,
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Additional 8% discount for prime numbers above MYR 500",
                            DiscountPercentage = 8,
                            IsActive = true,
                            MaxAmount = 9223372036854775807L,
                            MinAmount = 501L,
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Additional 10% discount for amounts ending in 5 above MYR 900",
                            DiscountPercentage = 10,
                            IsActive = true,
                            MaxAmount = 9223372036854775807L,
                            MinAmount = 901L,
                            Type = 2
                        });
                });

            modelBuilder.Entity("PartnerControlAPI.Models.ItemDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PartnerItemRef")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.Property<long>("UnitPrice")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.ToTable("ItemDetails");
                });

            modelBuilder.Entity("PartnerControlAPI.Models.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PartnerKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PartnerNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PartnerKey")
                        .IsUnique();

                    b.HasIndex("PartnerNo")
                        .IsUnique();

                    b.ToTable("Partners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            PartnerKey = "FAKEGOOGLE",
                            PartnerNo = "FG-00001",
                            Password = "FAKEPASSWORD1234"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            PartnerKey = "FAKEPEOPLE",
                            PartnerNo = "FG-00002",
                            Password = "FAKEPASSWORD4578"
                        });
                });

            modelBuilder.Entity("PartnerControlAPI.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("FinalAmount")
                        .HasColumnType("bigint");

                    b.Property<string>("PartnerKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PartnerRefNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<long>("TotalAmount")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalDiscount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PartnerKey", "PartnerRefNo")
                        .IsUnique();

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("PartnerControlAPI.Models.ItemDetail", b =>
                {
                    b.HasOne("PartnerControlAPI.Models.Transaction", "Transaction")
                        .WithMany("Items")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("PartnerControlAPI.Models.Transaction", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
